import{TestBed}from'@angular/core/testing';import{ActivatedRoute,convertToParamMap,Router}from'@angular/router';import{BehaviorSubject,of,throwError}from'rxjs';import{AuthService}from'../../core/auth/auth.service';import{PageResponse,Ticket,TicketQuery}from'../../core/models/ticket.models';import{TicketService}from'../../core/services/ticket.service';import{UserService}from'../../core/services/user.service';import{TicketsComponent}from'./tickets.component';

describe('TicketsComponent',()=>{
const ticket:Ticket={id:'ticket-1',ticketNumber:'INC-000001',title:'API indisponible',description:'Erreur',status:'IN_PROGRESS',priority:'CRITICAL',category:{id:'cat-1',name:'APPLICATION_ERROR',description:null},createdBy:{id:'user-1',firstName:'Alice',lastName:'Martin',email:'alice@test',role:'USER'},assignedTo:null,createdAt:'2026-08-21T10:00:00Z',updatedAt:'2026-08-21T10:00:00Z',resolvedAt:null,closedAt:null,firstResponseAt:null,responseDueAt:'2026-08-21T10:15:00Z',resolutionDueAt:'2026-08-21T12:00:00Z'};
const page=(content:Ticket[],number=0,totalPages=content.length?1:0):PageResponse<Ticket>=>({content,totalElements:content.length||0,totalPages,size:20,number,first:number===0,last:number+1>=totalPages});
let role:'USER'|'SUPPORT_N1'='USER';const service={getTickets:vi.fn()};const users={getSupportAgents:vi.fn()};const router={navigate:vi.fn()};let params$:BehaviorSubject<ReturnType<typeof convertToParamMap>>;
async function render(result=of(page([ticket])),params:Record<string,string>={}){service.getTickets.mockReturnValue(result);users.getSupportAgents.mockReturnValue(of([{id:'agent-1',firstName:'Nicolas',lastName:'Support',email:'n@test',role:'SUPPORT_N1'}]));params$=new BehaviorSubject(convertToParamMap(params));await TestBed.configureTestingModule({imports:[TicketsComponent],providers:[{provide:TicketService,useValue:service},{provide:UserService,useValue:users},{provide:AuthService,useValue:{getCurrentUser:()=>({id:'me',role})}},{provide:Router,useValue:router},{provide:ActivatedRoute,useValue:{queryParamMap:params$.asObservable()}}]}).compileComponents();const fixture=TestBed.createComponent(TicketsComponent);fixture.detectChanges();return fixture;}
beforeEach(()=>{TestBed.resetTestingModule();service.getTickets.mockReset();users.getSupportAgents.mockReset();router.navigate.mockReset();role='USER';vi.useRealTimers();});
it('displays loaded tickets and keeps click navigation',async()=>{const fixture=await render();expect(fixture.nativeElement.textContent).toContain('INC-000001');(fixture.nativeElement.querySelector('button.ticket-row')as HTMLButtonElement).click();expect(router.navigate).toHaveBeenCalledWith(['/app/tickets','ticket-1']);});
it('debounces search and returns to page zero',async()=>{vi.useFakeTimers();const fixture=await render();fixture.componentInstance.filters.controls.search.setValue('paiement');expect(router.navigate).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(351);expect(router.navigate).toHaveBeenCalledWith([],{relativeTo:expect.anything(),queryParams:expect.objectContaining({search:'paiement',page:0})});});
it('restores combined query params and sends them to the backend',async()=>{await render(of(page([])),{search:'paiement',status:'IN_PROGRESS',priority:'HIGH',assignedTo:'agent-1',page:'2',size:'50',sort:'status,asc'});expect(service.getTickets).toHaveBeenCalledWith(expect.objectContaining({search:'paiement',status:'IN_PROGRESS',priority:'HIGH',page:2,size:50,sort:'status,asc'}));});
it.each([['status','RESOLVED'],['priority','CRITICAL'],['sort','createdAt,asc']])('applies %s immediately and resets page',async(control,value)=>{const fixture=await render();fixture.componentInstance.filters.get(control)!.setValue(value);expect(router.navigate).toHaveBeenCalledWith([],{relativeTo:expect.anything(),queryParams:expect.objectContaining({[control]:value,page:0})});});
it('shows and loads the assigned agent filter for support',async()=>{role='SUPPORT_N1';const fixture=await render();expect(users.getSupportAgents).toHaveBeenCalled();expect(fixture.nativeElement.querySelector('.agent-filter').textContent).toContain('Nicolas Support');fixture.componentInstance.filters.controls.assignedTo.setValue('agent-1');expect(router.navigate).toHaveBeenCalledWith([],{relativeTo:expect.anything(),queryParams:expect.objectContaining({assignedTo:'agent-1',page:0})});});
it('does not show or load the agent filter for USER',async()=>{const fixture=await render();expect(fixture.nativeElement.querySelector('.agent-filter')).toBeNull();expect(users.getSupportAgents).not.toHaveBeenCalled();});
it('resets all filters',async()=>{const fixture=await render(of(page([])),{search:'incident',status:'NEW'});fixture.componentInstance.resetFilters();expect(router.navigate).toHaveBeenCalledWith([],{relativeTo:expect.anything(),queryParams:{page:0,size:20,sort:'createdAt,desc'}});});
it('navigates to previous and next pages within limits',async()=>{const fixture=await render(of(page([ticket],1,3)),{page:'1'});fixture.componentInstance.changePage(0);fixture.componentInstance.changePage(2);expect(router.navigate).toHaveBeenCalledTimes(2);expect(router.navigate).toHaveBeenLastCalledWith([],{relativeTo:expect.anything(),queryParams:expect.objectContaining({page:2})});});
it('changes page size and returns to zero',async()=>{const fixture=await render();fixture.componentInstance.filters.controls.size.setValue(50);expect(router.navigate).toHaveBeenCalledWith([],{relativeTo:expect.anything(),queryParams:expect.objectContaining({size:50,page:0})});});
it('distinguishes empty unfiltered and filtered states',async()=>{let fixture=await render(of(page([])));expect(fixture.nativeElement.textContent).toContain('Aucun ticket pour le moment.');TestBed.resetTestingModule();fixture=await render(of(page([])),{search:'absent'});expect(fixture.nativeElement.textContent).toContain('Aucun ticket ne correspond à vos critères.');expect(fixture.nativeElement.textContent).toContain('Réinitialiser les filtres');});
it('displays an HTTP error state',async()=>{const fixture=await render(throwError(()=>new Error('network')));expect(fixture.nativeElement.textContent).toContain('Impossible de charger les tickets');});
it('uses the expected title for each role',async()=>{let fixture=await render();expect(fixture.componentInstance.title).toBe('Mes tickets');TestBed.resetTestingModule();role='SUPPORT_N1';fixture=await render();expect(fixture.componentInstance.title).toBe('Tickets');});
it('navigates to ticket creation',async()=>{const fixture=await render();(fixture.nativeElement.querySelector('button.new-ticket')as HTMLButtonElement).click();expect(router.navigate).toHaveBeenCalledWith(['/app/tickets/new']);});
});
