import { HttpErrorResponse } from '@angular/common/http';
import { TestBed } from '@angular/core/testing';
import { of, Subject, throwError } from 'rxjs';
import { AuthService } from '../../../core/auth/auth.service';
import { AuthenticatedUser, Role } from '../../../core/models/auth.models';
import { Ticket } from '../../../core/models/ticket.models';
import { TicketService } from '../../../core/services/ticket.service';
import { UserService } from '../../../core/services/user.service';
import { TicketActionsComponent } from './ticket-actions.component';

describe('TicketActionsComponent',()=>{
 const ticket:Ticket={id:'ticket-1',ticketNumber:'INC-1',title:'Incident',description:'Description',status:'IN_PROGRESS',priority:'HIGH',category:{id:'c',name:'DATA',description:null},createdBy:{id:'u',firstName:'Alice',lastName:'Martin',email:'a@x',role:'USER'},assignedTo:null,createdAt:'2026-01-01Z',updatedAt:'2026-01-01Z',resolvedAt:null,closedAt:null,firstResponseAt:null,responseDueAt:'2026-01-01Z',resolutionDueAt:'2026-01-01Z'};
 const n1:AuthenticatedUser={id:'n1',firstName:'Nicolas',lastName:'Support',email:'n1@x',role:'SUPPORT_N1'};const n2:AuthenticatedUser={id:'n2',firstName:'Sophie',lastName:'Expert',email:'n2@x',role:'SUPPORT_N2'};
 let role:Role='SUPPORT_N1';const service={assignTicket:vi.fn(),changeStatus:vi.fn(),escalateTicket:vi.fn()};const users={getSupportAgents:vi.fn()};
 async function render(current=ticket){users.getSupportAgents.mockReturnValue(of([n1,n2]));await TestBed.configureTestingModule({imports:[TicketActionsComponent],providers:[{provide:TicketService,useValue:service},{provide:UserService,useValue:users},{provide:AuthService,useValue:{getCurrentUser:()=>({role})}}]}).compileComponents();const f=TestBed.createComponent(TicketActionsComponent);f.componentRef.setInput('ticket',current);f.detectChanges();return f;}
 beforeEach(()=>{TestBed.resetTestingModule();service.assignTicket.mockReset();service.changeStatus.mockReset();service.escalateTicket.mockReset();users.getSupportAgents.mockReset();role='SUPPORT_N1'});
 it('shows status, assignment and escalation to N1',async()=>{const text=(await render()).nativeElement.textContent;expect(text).toContain('Changer le statut');expect(text).toContain('Affecter');expect(text).toContain('Escalader vers N2');});
 it('shows only status action to N2',async()=>{role='SUPPORT_N2';const text=(await render()).nativeElement.textContent;expect(text).toContain('Changer le statut');expect(text).not.toContain('Escalader vers N2');expect(text).not.toContain('Affecter');});
 it('shows all actions to ADMIN',async()=>{role='ADMIN';const text=(await render()).nativeElement.textContent;expect(text).toContain('Affecter');expect(text).toContain('Escalader vers N2');});
 it('loads support agents and filters escalation targets',async()=>{const f=await render();expect(users.getSupportAgents).toHaveBeenCalled();expect(f.componentInstance.escalationTargets).toEqual([n2]);});
 it('renders loaded agents in assignment and only relevant escalation targets',async()=>{const f=await render();const assignee=(f.nativeElement.querySelector('#assignee')as HTMLSelectElement).textContent;const target=(f.nativeElement.querySelector('#target')as HTMLSelectElement).textContent;expect(assignee).toContain('Nicolas Support');expect(assignee).toContain('Sophie Expert');expect(target).toContain('Sophie Expert');expect(target).not.toContain('Nicolas Support');});
 it('shows an agent loading error when GET fails',async()=>{users.getSupportAgents.mockReturnValue(throwError(()=>new Error('network')));await TestBed.configureTestingModule({imports:[TicketActionsComponent],providers:[{provide:TicketService,useValue:service},{provide:UserService,useValue:users},{provide:AuthService,useValue:{getCurrentUser:()=>({role})}}]}).compileComponents();const f=TestBed.createComponent(TicketActionsComponent);f.componentRef.setInput('ticket',ticket);f.detectChanges();expect(f.nativeElement.textContent).toContain('Impossible de charger les agents support.');});
 it('calls status PUT and emits the updated ticket',async()=>{const updated={...ticket,status:'RESOLVED' as const};service.changeStatus.mockReturnValue(of(updated));const f=await render();const emitted=vi.fn();f.componentInstance.actionSucceeded.subscribe(emitted);f.componentInstance.statusControl.setValue('RESOLVED');f.componentInstance.changeStatus();expect(service.changeStatus).toHaveBeenCalledWith('ticket-1','RESOLVED');expect(emitted).toHaveBeenCalledWith(updated);});
 it('closes a RESOLVED ticket and preserves resolvedAt from the response',async()=>{const resolved={...ticket,status:'RESOLVED' as const,resolvedAt:'2026-08-21T18:00:00Z'};const closed={...resolved,status:'CLOSED' as const,closedAt:'2026-08-21T19:00:00Z'};service.changeStatus.mockReturnValue(of(closed));const f=await render(resolved);const emitted=vi.fn();f.componentInstance.actionSucceeded.subscribe(emitted);expect(f.componentInstance.transitions).toContain('CLOSED');f.componentInstance.statusControl.setValue('CLOSED');f.componentInstance.changeStatus();expect(service.changeStatus).toHaveBeenCalledWith('ticket-1','CLOSED');expect(emitted).toHaveBeenCalledWith(expect.objectContaining({status:'CLOSED',resolvedAt:resolved.resolvedAt,closedAt:closed.closedAt}));});
 it('shows the status 409 message',async()=>{service.changeStatus.mockReturnValue(throwError(()=>new HttpErrorResponse({status:409})));const f=await render();f.componentInstance.statusControl.setValue('RESOLVED');f.componentInstance.changeStatus();f.detectChanges();expect(f.nativeElement.textContent).toContain("Cette transition de statut n'est pas autorisée.");});
 it('handles status 403',async()=>{service.changeStatus.mockReturnValue(throwError(()=>new HttpErrorResponse({status:403})));const f=await render();f.componentInstance.statusControl.setValue('RESOLVED');f.componentInstance.changeStatus();f.detectChanges();expect(f.nativeElement.textContent).toContain("Vous n'êtes pas autorisé");});
 it('prevents double status submission',async()=>{service.changeStatus.mockReturnValue(new Subject<Ticket>());const f=await render();f.componentInstance.statusControl.setValue('RESOLVED');f.componentInstance.changeStatus();f.componentInstance.changeStatus();expect(service.changeStatus).toHaveBeenCalledTimes(1);});
 it('assigns the selected agent and emits the response',async()=>{const updated={...ticket,assignedTo:n1};service.assignTicket.mockReturnValue(of(updated));const f=await render();const emitted=vi.fn();f.componentInstance.actionSucceeded.subscribe(emitted);f.componentInstance.assigneeControl.setValue('n1');f.componentInstance.assign();expect(service.assignTicket).toHaveBeenCalledWith('ticket-1','n1');expect(emitted).toHaveBeenCalledWith(updated);});
 it('handles assignment errors',async()=>{service.assignTicket.mockReturnValue(throwError(()=>new HttpErrorResponse({status:403})));const f=await render();f.componentInstance.assigneeControl.setValue('n1');f.componentInstance.assign();expect(f.componentInstance.actionError()).toContain("Vous n'êtes pas autorisé");});
 it('requires a non-blank escalation reason',async()=>{const f=await render();f.componentInstance.reasonControl.setValue('   ');f.componentInstance.escalate();expect(service.escalateTicket).not.toHaveBeenCalled();});
 it('escalates to the selected N2 and emits ESCALATED',async()=>{const updated={...ticket,status:'ESCALATED' as const,assignedTo:n2};service.escalateTicket.mockReturnValue(of(updated));const f=await render();const emitted=vi.fn();f.componentInstance.actionSucceeded.subscribe(emitted);f.componentInstance.targetControl.setValue('n2');f.componentInstance.reasonControl.setValue(' Expertise N2 ');f.componentInstance.escalate();expect(service.escalateTicket).toHaveBeenCalledWith('ticket-1','n2','Expertise N2');expect(emitted).toHaveBeenCalledWith(updated);});
 it.each([403,409,422])('handles escalation HTTP %i',async status=>{service.escalateTicket.mockReturnValue(throwError(()=>new HttpErrorResponse({status})));const f=await render();f.componentInstance.reasonControl.setValue('Expertise');f.componentInstance.escalate();expect(f.componentInstance.actionError()).not.toBe('');});
 it('hides action forms for CLOSED tickets',async()=>{const f=await render({...ticket,status:'CLOSED'});expect(f.nativeElement.textContent).toContain('Ce ticket est fermé');expect(f.nativeElement.querySelector('.actions-grid')).toBeNull();});
});
