import{TestBed}from'@angular/core/testing';import{Router}from'@angular/router';import{of,Subject,throwError}from'rxjs';import{DashboardSummary}from'../../core/models/dashboard.models';import{DashboardService}from'../../core/services/dashboard.service';import{DashboardComponent}from'./dashboard.component';
describe('DashboardComponent',()=>{const ticket={id:'ticket-1',ticketNumber:'INC-000001',title:'Paiement indisponible',status:'NEW' as const,priority:'CRITICAL' as const,assignedTo:null,createdAt:'2026-08-21T10:00:00Z'};const summary:DashboardSummary={totalOpen:12,newTickets:3,inProgress:4,pending:2,escalated:1,criticalOpen:2,unassigned:5,responseSlaAtRisk:1,responseSlaBreached:2,resolutionSlaAtRisk:3,resolutionSlaBreached:4,priorityTickets:[ticket],recentTickets:[ticket]};const service={getSummary:vi.fn()};const router={navigate:vi.fn()};async function render(result=of(summary)){service.getSummary.mockReturnValue(result);await TestBed.configureTestingModule({imports:[DashboardComponent],providers:[{provide:DashboardService,useValue:service},{provide:Router,useValue:router}]}).compileComponents();const fixture=TestBed.createComponent(DashboardComponent);fixture.detectChanges();return fixture;}beforeEach(()=>{TestBed.resetTestingModule();service.getSummary.mockReset();router.navigate.mockReset();});
it('loads and displays KPI for support',async()=>{const f=await render();expect(service.getSummary).toHaveBeenCalled();expect(f.nativeElement.textContent).toContain('Tickets ouverts');expect(f.nativeElement.textContent).toContain('12');expect(f.nativeElement.textContent).toContain('Réponse dépassée');});
it('displays priority and recent lists',async()=>{const f=await render();expect(f.nativeElement.textContent).toContain('Tickets à traiter en priorité');expect(f.nativeElement.textContent).toContain('Tickets récents');expect(f.nativeElement.textContent).toContain('INC-000001');});
it('shows loading',async()=>{const pending=new Subject<DashboardSummary>();const f=await render(pending);expect(f.nativeElement.textContent).toContain('Chargement du tableau de bord');});
it('shows error and retries',async()=>{const f=await render(throwError(()=>new Error('network')));expect(f.nativeElement.textContent).toContain('Impossible de charger');service.getSummary.mockReturnValue(of(summary));(f.nativeElement.querySelector('.error button')as HTMLButtonElement).click();expect(service.getSummary).toHaveBeenCalledTimes(2);});
it.each([['Nouveaux',{status:'NEW'}],['Critiques ouverts',{priority:'CRITICAL'}],['Non assignés',{unassigned:true}]])('navigates from %s KPI to filtered tickets',async(label,query)=>{const f=await render();const button=[...f.nativeElement.querySelectorAll('.kpis button')].find((b:any)=>b.textContent.includes(label))as HTMLButtonElement;button.click();expect(router.navigate).toHaveBeenCalledWith(['/app/tickets'],{queryParams:query});});
it('opens a ticket detail',async()=>{const f=await render();(f.nativeElement.querySelector('.ticket')as HTMLButtonElement).click();expect(router.navigate).toHaveBeenCalledWith(['/app/tickets','ticket-1']);});
it('handles empty lists',async()=>{const f=await render(of({...summary,totalOpen:0,priorityTickets:[],recentTickets:[]}));expect(f.nativeElement.textContent).toContain('Aucune donnée opérationnelle');expect(f.nativeElement.textContent).toContain('Aucun ticket prioritaire');expect(f.nativeElement.textContent).toContain('Aucun ticket récent');});});
